import os
_HERE = os.path.dirname(os.path.abspath(__file__))
os.makedirs(os.path.join(_HERE, 'shots'), exist_ok=True)
import asyncio
from playwright.async_api import async_playwright
BASE = os.environ.get('APP_URL', 'http://localhost:4173')
results=[]; errors=[]
def check(c,m): results.append(('PASS' if c else 'FAIL', m))
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width':1360,'height':860}, timezone_id='Asia/Colombo')
        h = await ctx.new_page()
        h.on('pageerror', lambda e: errors.append(str(e)))
        h.on('console', lambda m: errors.append(m.text) if m.type=='error' else None)
        await h.goto(BASE)
        await h.click('text=Create an account')
        await h.fill('label:has-text("Full name") input', 'Hasith Ranaweera')
        await h.fill('input[type=email]', 'hasith@new.lk'); await h.fill('input[type=password]', 'secret123')
        await h.click('button:has-text("Create account")'); await h.wait_for_timeout(1800)
        check(await h.locator('h2:has-text("Welcome")').count() == 1, 'first sign-up lands as admin with a setup prompt')
        await h.screenshot(path=os.path.join(_HERE, 'shots', 'f1_welcome.png'))
        await h.click('button:has-text("Open Admin console")'); await h.wait_for_timeout(600)
        await h.fill('input[aria-label="New department name"]', 'Finance'); await h.click('button:has-text("Add department")'); await h.wait_for_timeout(900)
        await h.goto(BASE + '/#/admin/people'); await h.wait_for_timeout(700)
        row = h.locator('tr:has-text("Hasith")')
        await row.locator('select[aria-label="Department"]').select_option(label='Finance'); await h.wait_for_timeout(700)
        await row.locator('select[aria-label="Role"]').select_option('manager'); await h.wait_for_timeout(700)
        await h.goto(BASE + '/#/tasks'); await h.wait_for_timeout(1200)
        check('Finance' in await h.locator('.dept-switch .switcher').inner_text() and await h.locator('.tab.active:has-text("Home")').count() == 1,
              'after placing self in Finance, the admin (a manager) lands on Home in Finance')
        await h.goto(BASE + '/#/tasks/list'); await h.wait_for_timeout(800)
        await h.fill('.qa-title', 'First task'); await h.press('.qa-title', 'Enter'); await h.wait_for_timeout(700)
        check(await h.locator('.task-row:has-text("First task")').count() == 1, 'admin can add a task')
        # second person signs up
        ctx2 = await b.new_context(viewport={'width':1360,'height':860}, timezone_id='Asia/Colombo')
        m = await ctx2.new_page()
        await m.goto(BASE); await m.click('text=Create an account')
        await m.fill('label:has-text("Full name") input', 'New Person')
        await m.fill('input[type=email]', 'new@new.lk'); await m.fill('input[type=password]', 'secret123')
        await m.click('button:has-text("Create account")'); await m.wait_for_timeout(1500)
        check(await m.locator('h1:has-text("Waiting for approval")').count() == 1, 'second sign-up waits for approval')
        await h.reload(); await h.wait_for_timeout(1500)
        check(await h.locator('.dot-count').count() == 1, 'admin bell shows the sign-up')
        await b.close()
    for r in results: print(*r)
    print('ERRORS:', errors or 'none')
asyncio.run(main())
